# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bounded_reg_cpp <- function(dataModel, tuningParam, control) {
    .Call(`_quadrupen_bounded_reg_cpp`, dataModel, tuningParam, control)
}

elastic_net_cpp <- function(dataModel, tuningParam, control) {
    .Call(`_quadrupen_elastic_net_cpp`, dataModel, tuningParam, control)
}

ridge_cpp <- function(dataModel, tuningParam, control) {
    .Call(`_quadrupen_ridge_cpp`, dataModel, tuningParam, control)
}

