# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bounded_reg_cpp <- function(X, Y, Struct, LAMBDA1, N_LAMBDA, MIN_RATIO, PENSCALE, LAMBDA2, INTERCEPT, NORMALIZE, WEIGHTS, NAIVE, EPS, MAXITER, MAXFEAT, FUN, VERBOSE, SPARSE, BULLETPROOF) {
    .Call(`_quadrupen_bounded_reg_cpp`, X, Y, Struct, LAMBDA1, N_LAMBDA, MIN_RATIO, PENSCALE, LAMBDA2, INTERCEPT, NORMALIZE, WEIGHTS, NAIVE, EPS, MAXITER, MAXFEAT, FUN, VERBOSE, SPARSE, BULLETPROOF)
}

elastic_net_cpp <- function(BETA0, X, y, Struct, LAMBDA1, n_lambda, min_ratio, penscale, lambda2, intercept, normalize, weights, naive, eps, max_iter, max_feat, fun, verbose, sparse, usechol, monitor) {
    .Call(`_quadrupen_elastic_net_cpp`, BETA0, X, y, Struct, LAMBDA1, n_lambda, min_ratio, penscale, lambda2, intercept, normalize, weights, naive, eps, max_iter, max_feat, fun, verbose, sparse, usechol, monitor)
}

elastic_net2_cpp <- function(BETA0, X, y, S, lambda1, penscale, lambda2, intercept, xty, xbar, normx, normy, weights, eps, max_iter, max_feat, fun, verbose, sparse, usechol, monitor) {
    .Call(`_quadrupen_elastic_net2_cpp`, BETA0, X, y, S, lambda1, penscale, lambda2, intercept, xty, xbar, normx, normy, weights, eps, max_iter, max_feat, fun, verbose, sparse, usechol, monitor)
}

ridge_cpp <- function(X, Y, C, LAMBDA, NLAMBDA, LAMBDAMIN, LAMBDAMAX, INTERCEPT, NORMALIZE, WEIGHTS, VERBOSE) {
    .Call(`_quadrupen_ridge_cpp`, X, Y, C, LAMBDA, NLAMBDA, LAMBDAMIN, LAMBDAMAX, INTERCEPT, NORMALIZE, WEIGHTS, VERBOSE)
}

